# Data Preprocessing Tools

## 1. Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 2. Importing the dataset

In [20]:
# Leitura do dataset através do pandas
# Explicação do que é X e do que é Y
# X é variável independente e Y é variável dependente
# Porque foi colocado .values para transformar em arrays? Por que não usar dataframes
# e Series?
# Posso usar np.array(DataFrame) ao invés de usar o .values?

dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [26]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [27]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## 3. Taking care of missing data

In [28]:
# Existem duas formas de lidar com valores faltantes:
# Deletar as linhas com valores vazios. Muitos valores, não faz falta remover um ou outro
# Substituir os valores por outro (média, valor perto)
# O que significa imputer? A tradução mais próxima seria Imputador ou Preenchedor
# O imputer.fit(X[:,1:3]) substitui os valores faltantes pelos valores da média 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])

In [29]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## 4. Encoding  Categorical Variable

### 4.1 Encoding the Independent Variable

In [30]:
# Transformar a coluna Country, que é uma colunas com valores categóricos, em valores
# numéricos. Uso do OneHotEnconder
# O remainder='passthrough' garante que as outras colunas serão mantidas

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### 4.2 Encoding the Dependent Variable

In [33]:
# Por que usar LebelEncoder e não OneHotEncoder?
# Como o LabelEncoder escolher o que 0 e 1 significa? Nesse caso,No é 0 e 1 é Yes

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [34]:
print(y)

[0 1 0 0 1 1 0 1 0 1]
