# Data Preprocessing Tools

## 1. Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 2. Importing the dataset

In [4]:
# Leitura do dataset através do pandas
# Explicação do que é X e do que é Y
# X é variável independente e Y é variável dependente
# Porque foi colocado .values para transformar em arrays? Por que não usar dataframes
# e Series?
# Posso usar np.array(DataFrame) ao invés de usar o .values?

dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## 3. Taking care of missing data

In [7]:
# Existem duas formas de lidar com valores faltantes:
# Deletar as linhas com valores vazios. Muitos valores, não faz falta remover um ou outro
# Substituir os valores por outro (média, valor perto)
# O que significa imputer? A tradução mais próxima seria Imputador ou Preenchedor
# O imputer.fit(X[:,1:3]) substitui os valores faltantes pelos valores da média 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])

In [8]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## 4. Encoding  Categorical Variable

### 4.1 Encoding the Independent Variable

In [9]:
# Transformar a coluna Country, que é uma colunas com valores categóricos, em valores
# numéricos. Uso do OneHotEnconder
# O remainder='passthrough' garante que as outras colunas serão mantidas

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### 4.2 Encoding the Dependent Variable

In [11]:
# Por que usar LebelEncoder e não OneHotEncoder?
# Como o LabelEncoder escolher o que 0 e 1 significa? Nesse caso, 'No' é 0 e 1 é 'Yes'

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## 5. Splitting the dataset into the Training set and Test set

In [13]:
# Feature Scaling vem antes ou depois do Split the Dataset
# Resposta: vem depois
# Por quê? Porque Fazer o Feature Scaling antes de separar em teste e treinamento implica
# em aplicar a média de TODO o dataset para uma parte do dataset que, em tese, deveria ser nova.
# Ao aplicar antes, de certa forma você está contaminando o dataset teste com o dataset treinamento
# X_train, y_train, X_test, y_test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 1)

In [14]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [15]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [17]:
print(y_test)

[0 1]


## 6. Feature Scaling

In [21]:
# Por que Feature Scaling?
# Para evitar que algumas features (leia-se:colunas) não sejam dominadas por outras
# Feature Scaling: Standardization (fórmula) e Normalisation (fórmula)
# Standardization funciona sempre
# É melhor aplicar quando as features tem uma distribuição normal
# Devemos fazer feature scaler na dummy variables (variáveis binárias)
# Por que Standardisation deixa os números entre -3 e +3?

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:,3:])
X_test[:, 3:] = sc.transform(X_test[:,3:])

In [22]:
print(X_train)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [23]:
print(X_test)

[[0.0 1.0 0.0 -1.0000000000000002 -1.0000000000000002]
 [1.0 0.0 0.0 0.9999999999999999 0.9999999999999997]]
